data_loader:
  path: '/home/lephuocdat/Documents/dog_cat'
  batch_size: 64
  
transformer: 
  Rescale: [256,256]
  RandomCrop: 224
  RandomPerspective: None

model:
  module: 'models.mobilenetv3.mobilenetv3_small'
  class: 'MobileNetV3Small'
  MobileNetV3Small:
    num_classes: 2
    pretrained: True
    features_fixed: True
    
loss: 
  CrossEntropyLoss: None
     
optimizer:
  SGD:
    lr: 0.1
    momentum : 0.9

train:
  lr: 0.01
  epoch: 100
  device: 'cpu'
  

