data_loader:
  path: '/home/lephuocdat/Documents/dataset_bangcap/data_train_bangcap'
  batch_size: 64
  transformer: 'torchvision.transforms'
    
model:
  module: 'models.mobilenetv3.mobilenetv3_small'
  class: 'MobileNetV3Small'
  MobileNetV3Small:
    num_classes: 2
    pretrained: True
    features_fixed: True
    
loss: 'torch.nn'
     
optimizer: 'torch.optim'

train:
  epoch: 100
  device: 'cpu'
  checkpoint_path: 'checkpoints/bangcap/'

evaluation:
  best_checkpoint: 'checkpoints/bangcap/bangcap-0.944100022315979-2022-03-02-.pt'
  test_data: '/home/lephuocdat/Documents/dataset_bangcap/data_train_bangcap/test'
