data_loader:
  path: '/home/lephuocdat/Documents/dog_cat'
  batch_size: 64
  transformer: 'torchvision.transforms'
    
model:
  module: 'models.mobilenetv3.mobilenetv3_small'
  class: 'MobileNetV3Small'
  MobileNetV3Small:
    num_classes: 2
    pretrained: True
    features_fixed: True
    
loss: 'torch.nn'
     
optimizer: 'torch.optim'

train:
  epoch: 100
  device: 'cpu'
  

