torchvision.transforms:
  ToTensor:
    {}
  Resize: 
    size: [256,256]
  RandomPerspective:
    {}
  RandomAffine: 
    degrees: [-30,30]
  RandomHorizontalFlip: 
    {}
  GaussianBlur: 
    kernel_size: [3,3]        