torchvision.transforms:
  required: 
    ToTensor:
      {}
    Resize: 
      size: [240,240]
  random: 
    Pad:
       padding: 30
    ColorJitter:
      brightness: 0.25
      contrast: 0.25
      hue: 0.25
    GaussianBlur: 
      kernel_size: 5
    RandomAffine:
      degrees: 15
    RandomErasing:
      p: 0.2
    

  
   
